project_name: device-register
release:
  github:
    owner: TheCacophonyProject
    name: device-register
  name_template: '{{.Tag}}'

builds:
- id: device-register
  goos:
  - linux
  goarch:
  - arm
  - amd64
  goarm:
  - "7"
  main: ./cmd/device-register
  ldflags: -s -w -X main.version={{.Version}}
  binary: device-register

nfpms:
  - vendor: The Cacophony Project
    homepage: http://cacophony.org.nz/
    maintainer: Cacophony Developers <coredev@cacophony.org.nz>
    description: Register device to cacophony API
    license: GPL v3.0
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: _release/device-register.service
        dst: /etc/systemd/system/device-register.service
    scripts:
      postinstall: "_release/postinstall.sh"
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
